const { test, expect } = require("@playwright/test")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "../..")
const seed = JSON.parse(fs.readFileSync(path.join(root, "tmp/visual_review_seed.json"), "utf8"))
const output = path.join(root, "tmp/visual-review")

async function login(page) {
  await page.goto("/users/sign_in?locale=zh-CN")
  const form = page.locator('form[action="/users/sign_in"]')
  await form.locator('input[name="user[login]"]').fill(seed.email)
  await form.locator('input[name="user[password]"]').fill(seed.password)
  await form.locator('input[type="submit"]').click()
  await page.waitForLoadState("networkidle")
  await page.goto("/quotes?locale=zh-CN")
  await expect(page.locator(".quote-core-index")).toBeVisible()
}

test("quote core exposes customer page, PDF and Excel from one immutable version", async ({ page }) => {
  await login(page)
  const quoteId = seed.deal_id || seed.e2e_deal_id
  await page.goto(`/quotes/${quoteId}?tab=versions&locale=zh-CN`)
  await expect(page.locator(".quote-version-output")).toBeVisible()
  const version = page.locator(".quote-version-output article").first()
  const pdf = version.getByRole("link", { name: "PDF", exact: true })
  const excel = version.getByRole("link", { name: "Excel", exact: true })
  const customer = version.getByRole("link", { name: /客户页面|Customer page/ })
  await expect(pdf).toBeVisible()
  await expect(excel).toBeVisible()
  await expect(customer).toBeVisible()

  const pdfResponse = await page.request.get(await pdf.getAttribute("href"))
  expect(pdfResponse.ok()).toBeTruthy()
  expect(pdfResponse.headers()["content-type"]).toContain("application/pdf")
  expect((await pdfResponse.body()).subarray(0, 4).toString()).toBe("%PDF")
  const excelResponse = await page.request.get(await excel.getAttribute("href"))
  expect(excelResponse.ok()).toBeTruthy()
  expect(excelResponse.headers()["content-type"]).toContain("spreadsheetml")
  expect((await excelResponse.body()).subarray(0, 2).toString()).toBe("PK")

  const customerPage = await page.context().newPage()
  await customerPage.goto(await customer.getAttribute("href"))
  await expect(customerPage.locator(".buyer-storefront")).toBeVisible()
  await customerPage.close()
  await page.goto("/quotes?locale=zh-CN")
  await expect(page.locator("#primary-navigation")).toContainText(/报价|Quotes/)
  await expect(page.locator("#primary-navigation")).toContainText(/客户|Customers/)
  await expect(page.locator("#primary-navigation")).not.toContainText(/交易|Deal|收件箱|Inbox/)
  await page.goto("/imports?locale=zh-CN")
  await expect(page.locator(".import-hub")).toBeVisible()
  await page.goto("/document_design/edit?locale=zh-CN")
  await expect(page.locator(".document-design")).toBeVisible()
  fs.mkdirSync(output, { recursive: true })
  fs.writeFileSync(path.join(output, "quote-core-flow.json"), JSON.stringify({ result: "passed", quote_id: quoteId, outputs: ["customer_page", "pdf", "excel"], executed_at: new Date().toISOString() }, null, 2))
})
