class QuoteTemplate < ApplicationRecord
  DEFAULT_CLOSING_MESSAGE = "If you have questions, reply directly to this quote. Ready to proceed? Let us know.".freeze
  SAAS_BRANDING_FOOTER_TEXT = "This document was generated by Rubusoo.".freeze
  belongs_to :company
  has_many :quotes, foreign_key: :template_id, dependent: :nullify

  enum :layout_type, { classic: "classic", modern: "modern", industry: "industry" }, validate: true

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: { scope: :company_id }
  validates :accent_color,
            format: {
              with: /\A#(?:\h{3}|\h{6})\z/,
              message: "must be a valid HEX color like #1F4E79"
            }
  validates :font_family, presence: true
  validates :spec_label, presence: true
  validates :addon_label, presence: true

  validates :document_kind, inclusion: { in: %w[quotation proforma_invoice] }
  validates :layout_density, inclusion: { in: %w[compact standard spacious] }, allow_blank: true
  validates :thousand_separator, inclusion: { in: %w[comma space none] }, allow_blank: true
  validates :currency_display_mode, inclusion: { in: %w[symbol_prefix code_prefix code_suffix] }, allow_blank: true
  validates :logo_position, inclusion: { in: %w[left right center] }, allow_blank: true
  validates :amount_decimals, inclusion: { in: [ 0, 2 ] }, allow_nil: true

  BOOLEAN_FIELDS = %i[
    show_payment_term
    show_valid_until
    show_customer_owner
    show_notes
    show_logo
    show_negotiated_flag
    show_currency
    show_product_images
    show_terms_section
    show_signature_block
    show_images
    show_tax
    show_shipping
    excel_show_grid_lines
    show_closing_message
    show_saas_branding
    default_template
  ].freeze

  BOOLEAN_FIELDS.each do |field|
    validates field, inclusion: { in: [ true, false ] }
  end

  before_validation :normalize_slug
  before_validation :sync_legacy_fields
  before_validation :set_defaults

  scope :ordered, -> { order(default_template: :desc, created_at: :asc) }

  def resolved_table_label(kind)
    case kind.to_s
    when "description" then description_label.presence || "Description"
    when "qty" then qty_label.presence || "Qty"
    when "unit_price" then unit_price_label.presence || "Unit Price"
    when "line_total" then line_total_label.presence || "Line Total"
    else kind.to_s.titleize
    end
  end

  def show_images?
    show_images.nil? ? show_product_images : show_images
  end

  def show_product_images?
    show_images?
  end

  def resolved_document_title(kind = default_document_kind)
    if kind == "pi"
      pi_title.presence || "PROFORMA INVOICE"
    else
      quotation_title.presence || document_title.presence || "QUOTATION"
    end
  end

  def resolved_document_number_label(kind = default_document_kind)
    if kind == "pi"
      pi_number_label.presence || "PI #"
    else
      quotation_number_label.presence || document_number_label.presence || "Quote #"
    end
  end

  def resolved_footer_note(kind = default_document_kind)
    if kind == "pi"
      pi_footer_note.presence || footer_text.presence || footer_note
    else
      quotation_footer_note.presence || footer_text.presence || footer_note
    end
  end

  def resolved_closing_message
    return nil unless show_closing_message

    closing_message.to_s.strip.presence
  end

  def saas_branding_footer_text
    SAAS_BRANDING_FOOTER_TEXT
  end

  def normalize_document_kind(kind)
    case kind.to_s
    when "pi", "proforma_invoice" then "pi"
    else "quote"
    end
  end

  def default_document_kind
    normalize_document_kind(document_kind == "proforma_invoice" ? "pi" : "quote")
  end

  def make_default!
    transaction do
      company.quote_templates.where(default_template: true).where.not(id: id).update_all(default_template: false)
      update!(default_template: true)
    end
  end

  private

  def normalize_slug
    base = slug.presence || name
    self.slug = base.to_s.parameterize if base.present?
  end

  def sync_legacy_fields
    self.show_product_images = show_images if has_attribute?(:show_product_images)
    self.show_images = show_product_images if show_images.nil?
    self.footer_note = footer_text if footer_text.present? && footer_note.blank?
    self.footer_text = footer_note if footer_text.blank? && footer_note.present?
  end

  def set_defaults
    self.name = "Template" if name.blank?
    self.layout_type ||= "classic"
    self.accent_color = "#1F4E79" if accent_color.blank?
    self.font_family = "Noto Sans" if font_family.blank?
    self.footer_text ||= ""
    self.closing_message = DEFAULT_CLOSING_MESSAGE if closing_message.nil?
    self.show_images = true if show_images.nil?
    self.show_tax = true if show_tax.nil?
    self.show_shipping = true if show_shipping.nil?
    self.show_closing_message = true if show_closing_message.nil?
    self.show_saas_branding = false if show_saas_branding.nil?
    self.excel_show_grid_lines = false if excel_show_grid_lines.nil?
    self.layout_density = "standard" if layout_density.blank?
    self.amount_decimals = 2 if amount_decimals.nil?
    self.thousand_separator = "comma" if thousand_separator.blank?
    self.currency_display_mode = "symbol_prefix" if currency_display_mode.blank?
    self.logo_position = "right" if logo_position.blank?
    self.description_label = "Description" if description_label.blank?
    self.qty_label = "Qty" if qty_label.blank?
    self.unit_price_label = "Unit Price" if unit_price_label.blank?
    self.line_total_label = "Line Total" if line_total_label.blank?
    self.spec_label = "Spec" if spec_label.blank?
    self.addon_label = "Add-on" if addon_label.blank?
  end
end
