class QuoteTemplate < ApplicationRecord
  CUSTOM_FIELD_TYPES = %w[text number date multiline].freeze
  DEFAULT_CLOSING_MESSAGE = "If you have questions, reply directly to this quote. Ready to proceed? Let us know.".freeze
  SAAS_BRANDING_FOOTER_TEXT = "This document was generated by Rubusoo.".freeze
  OUTPUT_LOCALES = {
    "en" => "English",
    "zh-CN" => "简体中文",
    "es-419" => "Espanol (LatAm)"
  }.freeze
  IMAGE_CONTENT_TYPES = %w[image/png image/jpeg image/webp image/gif image/svg+xml].freeze
  MAX_SIGNATURE_IMAGE_SIZE = 5.megabytes
  MAX_WATERMARK_IMAGE_SIZE = 8.megabytes
  MAX_TEMPLATE_LABEL_LENGTH = 80
  MAX_TEMPLATE_TITLE_LENGTH = 180
  MAX_TEMPLATE_NUMBER_LABEL_LENGTH = 80
  MAX_TEMPLATE_FOOTER_LENGTH = 4000
  MAX_SCOPE_OF_SUPPLY_DEFAULT_CONTENT_LENGTH = 4000
  MAX_CLOSING_MESSAGE_LENGTH = 2000
  MAX_WATERMARK_TEXT_LENGTH = 120
  MAX_SIGNATURE_NAME_LENGTH = 120
  ADVANCED_DEFAULT_KEYS = %w[
    trade_terms_hs_code
    trade_terms_warranty_scope_note
    trade_terms_support_scope_note
    trade_terms_validity_clause_note
    trade_terms_delivery_commitment_note
    trade_terms_payment_clause_note
    logistics_freight_note
    logistics_container_type
    logistics_shipping_scope_note
    logistics_container_loading_note
  ].freeze
  ADVANCED_VISIBILITY_KEYS = %w[
    show_trade_terms_advanced
    show_logistics_block
  ].freeze
  belongs_to :company
  has_many :quotes, foreign_key: :template_id, dependent: :nullify
  has_one_attached :watermark_image
  has_one_attached :signature_image

  enum :layout_type, { classic: "classic", modern: "modern", industry: "industry" }, validate: true

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: { scope: :company_id }
  validates :description_label, :spec_label, :addon_label, :qty_label, :unit_price_label, :line_total_label, :scope_of_supply_label,
            length: { maximum: MAX_TEMPLATE_LABEL_LENGTH }
  validates :quotation_title, :pi_title, :document_title, length: { maximum: MAX_TEMPLATE_TITLE_LENGTH }, allow_blank: true
  validates :quotation_number_label, :pi_number_label, :document_number_label,
            length: { maximum: MAX_TEMPLATE_NUMBER_LABEL_LENGTH }, allow_blank: true
  validates :quotation_footer_note, :pi_footer_note, :footer_text, length: { maximum: MAX_TEMPLATE_FOOTER_LENGTH }, allow_blank: true
  validates :default_scope_of_supply_content, length: { maximum: MAX_SCOPE_OF_SUPPLY_DEFAULT_CONTENT_LENGTH }, allow_blank: true
  validates :closing_message, length: { maximum: MAX_CLOSING_MESSAGE_LENGTH }, allow_blank: true
  validates :watermark_text, length: { maximum: MAX_WATERMARK_TEXT_LENGTH }, allow_blank: true
  validates :signature_name, length: { maximum: MAX_SIGNATURE_NAME_LENGTH }, allow_blank: true
  validates :accent_color,
            format: {
              with: /\A#(?:\h{3}|\h{6})\z/,
              message: "must be a valid HEX color like #1F4E79"
            }
  validates :font_family, presence: true
  validates :spec_label, presence: true
  validates :addon_label, presence: true

  validates :document_kind, inclusion: { in: %w[quotation proforma_invoice] }
  validates :layout_density, inclusion: { in: %w[compact standard spacious] }, allow_blank: true
  validates :thousand_separator, inclusion: { in: %w[comma space none] }, allow_blank: true
  validates :currency_display_mode, inclusion: { in: %w[symbol_prefix code_prefix code_suffix] }, allow_blank: true
  validates :logo_position, inclusion: { in: %w[left right center] }, allow_blank: true
  validates :amount_decimals, inclusion: { in: [ 0, 2 ] }, allow_nil: true
  validates :watermark_opacity, inclusion: { in: 3..40 }, allow_nil: true
  validates :webview_locale, inclusion: { in: OUTPUT_LOCALES.keys }
  validates :public_link_locale, inclusion: { in: OUTPUT_LOCALES.keys }
  validates :pdf_locale, inclusion: { in: OUTPUT_LOCALES.keys }
  validates :excel_locale, inclusion: { in: OUTPUT_LOCALES.keys }
  validate :signature_image_constraints
  validate :watermark_image_constraints
  validate :custom_field_definitions_are_valid

  BOOLEAN_FIELDS = %i[
    show_payment_term
    show_valid_until
    show_customer_owner
    show_notes
    show_scope_of_supply
    show_logo
    show_negotiated_flag
    show_currency
    show_product_images
    show_terms_section
    show_signature_block
    show_watermark
    show_images
    show_tax
    show_shipping
    excel_show_grid_lines
    show_closing_message
    show_saas_branding
    show_public_revision_summary
    show_pdf_revision_summary
    show_excel_revision_summary
    enable_advanced_by_default
    default_template
  ].freeze

  BOOLEAN_FIELDS.each do |field|
    validates field, inclusion: { in: [ true, false ] }
  end

  before_validation :normalize_slug
  before_validation :sync_legacy_fields
  before_validation :sync_visual_toggles
  before_validation :set_defaults

  scope :ordered, -> { order(default_template: :desc, created_at: :asc) }

  def resolved_table_label(kind)
    case kind.to_s
    when "description" then description_label.presence || I18n.t("quote_document.labels.description")
    when "qty" then qty_label.presence || I18n.t("quote_document.labels.qty")
    when "unit_price" then unit_price_label.presence || I18n.t("quote_document.labels.unit_price")
    when "line_total" then line_total_label.presence || I18n.t("quote_document.labels.line_total")
    else kind.to_s.titleize
    end
  end

  def show_images?
    show_images.nil? ? show_product_images : show_images
  end

  def show_product_images?
    show_images?
  end

  def resolved_document_title(kind = default_document_kind)
    if kind == "pi"
      pi_title.presence || I18n.t("quote_document.titles.pi")
    else
      quotation_title.presence || document_title.presence || I18n.t("quote_document.titles.quotation")
    end
  end

  def resolved_document_number_label(kind = default_document_kind)
    if kind == "pi"
      pi_number_label.presence || I18n.t("quote_document.labels.pi_number")
    else
      quotation_number_label.presence || document_number_label.presence || I18n.t("quote_document.labels.quote_number")
    end
  end

  def resolved_scope_of_supply_label
    scope_of_supply_label.to_s.strip.presence || I18n.t("quote_templates.defaults.scope_of_supply_label")
  end

  def resolved_footer_note(kind = default_document_kind)
    if kind == "pi"
      pi_footer_note.presence || footer_text.presence || footer_note
    else
      quotation_footer_note.presence || footer_text.presence || footer_note
    end
  end

  def resolved_closing_message
    return nil unless show_closing_message

    closing_message.to_s.strip.presence
  end

  def saas_branding_footer_text
    SAAS_BRANDING_FOOTER_TEXT
  end

  def normalize_document_kind(kind)
    case kind.to_s
    when "pi", "proforma_invoice" then "pi"
    else "quote"
    end
  end

  def default_document_kind
    normalize_document_kind(document_kind == "proforma_invoice" ? "pi" : "quote")
  end

  def output_locale_for(channel)
    case channel.to_sym
    when :webview then normalized_output_locale(webview_locale)
    when :public_link then normalized_output_locale(public_link_locale)
    when :pdf then normalized_output_locale(pdf_locale)
    when :excel then normalized_output_locale(excel_locale)
    else "en"
    end
  end

  def custom_field_definitions
    Array(custom_fields).map(&:with_indifferent_access)
  end

  def output_locale_options
    OUTPUT_LOCALES.map { |value, label| [ label, value ] }
  end

  def advanced_defaults_data
    normalized_string_hash(advanced_defaults, allowed_keys: ADVANCED_DEFAULT_KEYS)
  end

  def advanced_visibility_defaults_data
    normalized_boolean_hash(advanced_visibility_defaults, allowed_keys: ADVANCED_VISIBILITY_KEYS)
  end

  def make_default!
    transaction do
      company.quote_templates.where(default_template: true).where.not(id: id).update_all(default_template: false)
      update!(default_template: true)
    end
  end

  private

  def custom_field_definitions_are_valid
    keys = custom_field_definitions.map { |field| field[:key].to_s }
    errors.add(:custom_fields, "contain duplicate keys") if keys.uniq.size != keys.size
    custom_field_definitions.each do |field|
      errors.add(:custom_fields, "need a key and label") if field.values_at(:key, :label).any?(&:blank?)
      errors.add(:custom_fields, "have an unsupported type") unless field[:type].to_s.presence_in(CUSTOM_FIELD_TYPES)
    end
  end

  def normalize_slug
    base = slug.presence || name
    self.slug = base.to_s.parameterize if base.present?
  end

  def sync_legacy_fields
    self.show_product_images = show_images if has_attribute?(:show_product_images)
    self.show_images = show_product_images if show_images.nil?
    self.footer_note = footer_text if footer_text.present? && footer_note.blank?
    self.footer_text = footer_note if footer_text.blank? && footer_note.present?
  end

  def set_defaults
    self.name = "Template" if name.blank?
    self.layout_type ||= "classic"
    self.accent_color = "#1F4E79" if accent_color.blank?
    self.font_family = "Noto Sans" if font_family.blank?
    self.footer_text ||= ""
    self.default_scope_of_supply_content = "" if default_scope_of_supply_content.nil?
    self.closing_message = DEFAULT_CLOSING_MESSAGE if closing_message.nil?
    self.show_images = true if show_images.nil?
    self.show_tax = true if show_tax.nil?
    self.show_shipping = true if show_shipping.nil?
    self.show_closing_message = true if show_closing_message.nil?
    self.show_saas_branding = true if show_saas_branding.nil?
    self.show_public_revision_summary = true if show_public_revision_summary.nil?
    self.show_pdf_revision_summary = true if show_pdf_revision_summary.nil?
    self.show_excel_revision_summary = true if show_excel_revision_summary.nil?
    self.enable_advanced_by_default = false if enable_advanced_by_default.nil?
    self.show_scope_of_supply = false if show_scope_of_supply.nil?
    self.show_watermark = false if show_watermark.nil?
    self.excel_show_grid_lines = false if excel_show_grid_lines.nil?
    self.layout_density = "standard" if layout_density.blank?
    self.amount_decimals = 2 if amount_decimals.nil?
    self.thousand_separator = "comma" if thousand_separator.blank?
    self.currency_display_mode = "symbol_prefix" if currency_display_mode.blank?
    self.logo_position = "right" if logo_position.blank?
    self.description_label = "Description" if description_label.blank?
    self.qty_label = "Qty" if qty_label.blank?
    self.unit_price_label = "Unit Price" if unit_price_label.blank?
    self.line_total_label = "Line Total" if line_total_label.blank?
    self.spec_label = "Spec" if spec_label.blank?
    self.addon_label = "Add-on" if addon_label.blank?
    self.watermark_text = "" if watermark_text.nil?
    self.watermark_opacity = 12 if watermark_opacity.nil?
    self.signature_name = "" if signature_name.nil?
    self.webview_locale = normalized_output_locale(webview_locale)
    self.public_link_locale = normalized_output_locale(public_link_locale)
    self.pdf_locale = normalized_output_locale(pdf_locale)
    self.excel_locale = normalized_output_locale(excel_locale)
    self.advanced_defaults = {} if advanced_defaults.blank?
    self.advanced_visibility_defaults = {} if advanced_visibility_defaults.blank?
  end

  def sync_visual_toggles
    has_signature_upload = (respond_to?(:signature_image) && signature_image.attached?) || attachment_changes["signature_image"].present?
    has_signature_name = signature_name.to_s.strip.present?
    has_watermark_upload = (respond_to?(:watermark_image) && watermark_image.attached?) || attachment_changes["watermark_image"].present?

    self.show_signature_block = true if has_signature_upload || has_signature_name
    self.show_watermark = true if watermark_text.to_s.strip.present? || has_watermark_upload
    self.advanced_defaults = normalized_string_hash(advanced_defaults, allowed_keys: ADVANCED_DEFAULT_KEYS)
    self.advanced_visibility_defaults = normalized_boolean_hash(advanced_visibility_defaults, allowed_keys: ADVANCED_VISIBILITY_KEYS)
  end

  def normalized_output_locale(value)
    OUTPUT_LOCALES.key?(value.to_s) ? value.to_s : "en"
  end

  def normalized_string_hash(raw, allowed_keys:)
    source = if raw.respond_to?(:to_unsafe_h)
      raw.to_unsafe_h
    elsif raw.is_a?(Hash)
      raw
    else
      {}
    end

    allowed_keys.each_with_object({}) do |key, acc|
      value = source[key] || source[key.to_sym]
      cleaned = value.to_s.strip
      acc[key] = cleaned if cleaned.present?
    end
  end

  def normalized_boolean_hash(raw, allowed_keys:)
    source = if raw.respond_to?(:to_unsafe_h)
      raw.to_unsafe_h
    elsif raw.is_a?(Hash)
      raw
    else
      {}
    end
    caster = ActiveModel::Type::Boolean.new

    allowed_keys.each_with_object({}) do |key, acc|
      next unless source.key?(key) || source.key?(key.to_sym)

      acc[key] = caster.cast(source[key] || source[key.to_sym])
    end
  end

  def signature_image_constraints
    return unless signature_image.attached?

    if !IMAGE_CONTENT_TYPES.include?(signature_image.blob.content_type)
      errors.add(:signature_image, "must be an image (PNG, JPG, WEBP, GIF, or SVG)")
    end
    if signature_image.blob.byte_size > MAX_SIGNATURE_IMAGE_SIZE
      errors.add(:signature_image, "must be smaller than #{MAX_SIGNATURE_IMAGE_SIZE / 1.megabyte}MB")
    end
  end

  def watermark_image_constraints
    return unless watermark_image.attached?

    if !IMAGE_CONTENT_TYPES.include?(watermark_image.blob.content_type)
      errors.add(:watermark_image, "must be an image (PNG, JPG, WEBP, GIF, or SVG)")
    end
    if watermark_image.blob.byte_size > MAX_WATERMARK_IMAGE_SIZE
      errors.add(:watermark_image, "must be smaller than #{MAX_WATERMARK_IMAGE_SIZE / 1.megabyte}MB")
    end
  end
end
